#!/usr/bin/python

import re
import time

def getstats():
    rv = {}
    f.seek(0)
    for i in range(2): f.readline()
    for line in f:
        (name, data) = line.strip().split(":")
        data = data.split()
        rv[name] = [int(x) for x in data]

    return rv

if __name__ == "__main__":
    f = open("/proc/net/dev")
    rx = re.compile("(?!(docker0|lo|veth[0-9a-f]+|virbr[0-9]+(-nic)?|vnet0)$)")
    old = getstats()
    while True:
        time.sleep(2)
        new = getstats()

        ifaces = sorted([iface for iface in set(old) & set(new) if rx.match(iface)])
        for iface in ifaces:
            print("%12s:  RX: %6.2f Mbps (%4d pps)  " \
                "TX: %6.2f Mbps (%4d pps)" % \
                (iface,
                 (new[iface][0] - old[iface][0]) / 250000.0,
                 (new[iface][1] - old[iface][1]) / 2,
                 (new[iface][8] - old[iface][8]) / 250000.0,
                 (new[iface][9] - old[iface][9]) / 2
                ))
        old = new
